# Generated by Django 4.1.6 on 2024-01-03 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_paymentinfo_paymentinfostudent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentInfoStudent',
            new_name='PaymentInfo',
        ),
    ]
