# Generated by Django 4.1.6 on 2024-01-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_paymentinfostudent_paymentinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bedinfohistory',
            options={'verbose_name': "To'lov info tarixi", 'verbose_name_plural': "To'lov infolar tarixi"},
        ),
        migrations.AlterModelOptions(
            name='paymentinfo',
            options={'verbose_name': "To'lov info", 'verbose_name_plural': "To'lov infolar"},
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=10, verbose_name='JInsi'),
        ),
    ]
