# Generated by Django 4.1.6 on 2024-01-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_bedinfohistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedinfohistory',
            name='student_id',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='student_id',
            field=models.CharField(max_length=12),
        ),
    ]
