# Generated by Django 4.1.6 on 2024-01-07 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedinfohistory',
            name='bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_history', to='main.bed'),
        ),
    ]
