# Generated by Django 4.1.6 on 2024-01-07 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_bedinfohistory_bed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedinfohistory',
            name='bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_history', to='main.bed'),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='main.bed'),
        ),
    ]
