# Generated by Django 4.1.6 on 2024-01-07 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_bedinfohistory_bed_alter_paymentinfo_bed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('receipt_number_add', models.CharField(max_length=20, verbose_name='Kvitansiya raqami')),
                ('payment_amount_add', models.CharField(max_length=16, verbose_name="To'langan summa")),
                ('payment_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_payments', to='main.paymentinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
