# Generated by Django 4.1.6 on 2024-01-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_addpaymentinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpaymentinfo',
            name='student_id',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
