# Generated by Django 4.1.6 on 2024-01-07 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_bedinfohistory_receipt_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPaymentInfoHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('receipt_number_add', models.CharField(max_length=20, verbose_name='Kvitansiya raqami')),
                ('payment_amount_add', models.CharField(max_length=16, verbose_name="To'langan summa")),
                ('student_id', models.CharField(blank=True, max_length=12, null=True)),
                ('payment_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_payments_history', to='main.paymentinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
