# Generated by Django 4.1.6 on 2024-01-07 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_addpaymentinfohistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpaymentinfohistory',
            name='payment_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_payments_history', to='main.bedinfohistory'),
        ),
    ]
