# Generated by Django 4.1.6 on 2024-01-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_addpaymentinfohistory_payment_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('monthly_payment', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='addpaymentinfo',
            options={'verbose_name': "To'lov kvitansiya", 'verbose_name_plural': "To'lov kvitansiyalari"},
        ),
        migrations.AlterModelOptions(
            name='addpaymentinfohistory',
            options={'verbose_name': "To'lov kvitansiya tarixi", 'verbose_name_plural': "To'lov kvitansiyalari tarixi"},
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Ariza', 'verbose_name_plural': 'Arizalar'},
        ),
    ]
