# Generated by Django 4.1.6 on 2024-01-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_monthlypayment_alter_addpaymentinfo_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonthlyPayment',
            new_name='MonthlyPaymentPrice',
        ),
        migrations.RenameField(
            model_name='monthlypaymentprice',
            old_name='monthly_payment',
            new_name='price',
        ),
    ]
